### PR TITLE
fix trailing slashes from --chain=value/

### LINKED ISSUE #391: custom --chain flag value should ignore trailing '/'s
```
~/Library/EthereumClassic/testes  ⟠ ..
~/Library/EthereumClassic  ⟠ geth --fast --chain testes/
F1026 15:46:09.146309 cmd/geth/flag.go:790] invalid chainID: JSON 'id' value in external config file (testes) must match name of parent subdir (testes/)
```

### PR DESCRIPTION
**Pull request by whilei**
solution: remove them, both as *nix (`/`) and windows separators (`\`)

fixes #391

### CODE REVIEW

File: cmd/geth/flag.go [hunk 1]
```diff
@@ -155,6 +155,12 @@ func mustMakeChainIdentity(ctx *cli.Context) (identity string) {
 		cacheChainIdentity = identity
 	}()
 
+	if chainFlagVal := ctx.GlobalString(aliasableName(ChainIdentityFlag.Name, ctx)); chainFlagVal != "" && strings.HasSuffix(chainFlagVal, "/") || strings.HasSuffix(chainFlagVal, "\\") {
```
Comment (tzdybal) [inline cmd/geth/flag.go]: We can use [`path.filepath.Separator`](https://golang.org/pkg/path/filepath/#pkg-constants), or even [`path.filepath.Clean`](https://golang.org/pkg/path/filepath/#Clean) to simplify the code.

File: cmd/geth/flag.go [hunk 2]
```diff
@@ -155,6 +155,12 @@ func mustMakeChainIdentity(ctx *cli.Context) (identity string) {
...
+		suff := string(chainFlagVal[len(chainFlagVal)-1])
+		chainFlagVal = strings.Replace(chainFlagVal, suff, "", 1)
```
Comment (tzdybal) [inline cmd/geth/flag.go]: Can't we just "chop" the string, remove last character, instead of doing `strings.Replace`, like:
`chainFlagVal = chainFlagVal[:len(chainFlagVal)-1]` (then we could even inline this in following line)?
(And I you decide to do `Clean` as mentioned above, the problem won't exist anyways).
